name: Publish from Tag

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]*'

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    uses: codenautas/.github/.github/workflows/npm-publish-from-tag.yaml@main
    with:
      node_version: '24'
